service: import-service
configValidationMode: error

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: eu-west-1
  apiGateway:
    shouldStartNameWithService: true

  iamRoleStatements:
    - Effect: "Allow"
      Action: "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::${self:custom.bucketName}"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::${self:custom.bucketName}/*"

custom:
  bucketName: nodejs-aws-import-service
  webpack:
    webpackConfig: webpack.config.js
    includeModules: false

plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation

functions:
  importProductsFile:
    handler: handlers/importProductsFile.default
    events:
      - http:
          method: get
          path: /import
          request:
            parameters:
              querystrings:
                name: true
          cors: true
          reqValidatorName: onlyQueryParams
  importFileParcer:
    handler: handlers/importFileParcer.default
    events:
      - s3:
          bucket: ${self:custom.bucketName}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

resources:
  Resources:
    onlyQueryParams:
      Type: "AWS::ApiGateway::RequestValidator"
      Properties:
        Name: 'only-query-params'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: false
        ValidateRequestParameters: true
